# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class {{ .FormulaName }} < Formula
  desc "{{ .Description }}"
  homepage "https://tealbase.com"
  version "{{ .Version }}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tealbase/cli/releases/download/v{{ .Version }}/tealbase_darwin_arm64.tar.gz"
      sha256 "{{ .Checksum.tealbase_darwin_arm64 }}"

      def install
        bin.install "tealbase"
        (bash_completion/"tealbase").write `#{bin}/tealbase completion bash`
        (fish_completion/"tealbase.fish").write `#{bin}/tealbase completion fish`
        (zsh_completion/"_tealbase").write `#{bin}/tealbase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tealbase/cli/releases/download/v{{ .Version }}/tealbase_darwin_amd64.tar.gz"
      sha256 "{{ .Checksum.tealbase_darwin_amd64 }}"

      def install
        bin.install "tealbase"
        (bash_completion/"tealbase").write `#{bin}/tealbase completion bash`
        (fish_completion/"tealbase.fish").write `#{bin}/tealbase completion fish`
        (zsh_completion/"_tealbase").write `#{bin}/tealbase completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tealbase/cli/releases/download/v{{ .Version }}/tealbase_linux_arm64.tar.gz"
      sha256 "{{ .Checksum.tealbase_linux_arm64 }}"

      def install
        bin.install "tealbase"
        (bash_completion/"tealbase").write `#{bin}/tealbase completion bash`
        (fish_completion/"tealbase.fish").write `#{bin}/tealbase completion fish`
        (zsh_completion/"_tealbase").write `#{bin}/tealbase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tealbase/cli/releases/download/v{{ .Version }}/tealbase_linux_amd64.tar.gz"
      sha256 "{{ .Checksum.tealbase_linux_amd64 }}"

      def install
        bin.install "tealbase"
        (bash_completion/"tealbase").write `#{bin}/tealbase completion bash`
        (fish_completion/"tealbase.fish").write `#{bin}/tealbase completion fish`
        (zsh_completion/"_tealbase").write `#{bin}/tealbase completion zsh`
      end
    end
  end
end
